---
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAME_SPACE}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  namespace: ${NAME_SPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
    spec:
      imagePullSecrets:
        - name: regcred  # Secret untuk menarik image dari DigitalOcean Container Registry
      containers:
        - name: ${PROJECT_NAME}
          image: registry.digitalocean.com/archanist-dev/${CONTAINER_REGISTRY}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "800Mi"
              cpu: "500m"
            requests:
              memory: "400Mi"
              cpu: "250m"
          command: ["npm", "start"]
---
apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME}
  namespace: ${NAME_SPACE}
spec:
  selector:
    app: ${PROJECT_NAME}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${PROJECT_NAME}
  namespace: ${NAME_SPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${PROJECT_NAME}
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75 #sesuaikan dengan keinginan
  behavior:
      scaleUp:
        stabilizationWindowSeconds: 10
        policies:
        - type: Pods
          value: 3
          periodSeconds: 5
      scaleDown:
        stabilizationWindowSeconds: 10
        policies:
        - type: Pods
          value: 1
          periodSeconds: 5