name: Docker Image CI/CD to K3s

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: registry.digitalocean.com/archanist-dev
  IMAGE_NAME: landing-pages-01
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate with DigitalOcean
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry
      run: doctl registry login

    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        build-args: VERSION=${{ env.IMAGE_TAG }}

    - name: Update Kubernetes manifest with new image tag
      run: |
        sed -i "s|image: registry.digitalocean.com/archanist-dev/landing-pages-01:.*|image: registry.digitalocean.com/archanist-dev/landing-pages-01:${{ env.IMAGE_TAG }}|" .deployments/test.yaml

    - name: Replace variables in Kubernetes manifest
      run: |
        export PROJECT_NAME="landing-pages-01"
        export NAME_SPACE="test"
        export IMAGE_TAG="${{ github.sha }}"
        envsubst < .deployments/test.yaml > .deployments/test.yaml.tmp && mv .deployments/test.yaml.tmp .deployments/test.yaml

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "latest"

    - name: Configure Kubernetes credentials
      run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy to K3s using kubectl
      run: |
        kubectl apply -f .deployments/test.yaml
        kubectl rollout restart deployment landing-pages