name: CI/CD - Deploy React App to Kubernetes on Digital Ocean

on:
  push:
    branches:
      - main
      - staging
      - publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      # Ganti dengan nama container registry Digital Ocean Anda
      REGISTRY: registry.digitalocean.com/archanist-dev
      # Ganti dengan nama image yang Anda inginkan
      IMAGE_NAME: landing-page-01

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DigitalOcean Container Registry with service account
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Deploy to Kubernetes
        uses: kubectl-action/kubectl@v0.7.0
        env:
          # Ganti dengan nama klaster Kubernetes Anda
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          # Tentukan namespace berdasarkan branch
          K8S_NAMESPACE: ${{ github.ref == 'refs/heads/main' && 'production' || (github.ref == 'refs/heads/staging' && 'staging' || 'publish') }}
          # Ganti dengan path ke folder .deployments Anda
          KUBECTL_APPLY: true
          KUBECTL_APPLY_FLAGS: "-n ${{ env.K8S_NAMESPACE }} -f ./.deployments"
          # Update image di deployment
          KUBECTL_PATCH: true
          KUBECTL_PATCH_TARGET: "deployment/${{ env.IMAGE_NAME }}"
          KUBECTL_PATCH_STRATEGY: strategic
          KUBECTL_PATCH_FIELD: "spec.template.spec.containers[0].image"
          KUBECTL_PATCH_VALUE: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"