name: Docker Image CI/CD to K3s

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: registry.digitalocean.com/archanist-dev
  IMAGE_NAME: landing-pages-01
  IMAGE_TAG: ${{ github.sha }}
  DEPLOYMENT_FILE: .deployments/test.yaml
  PROJECT_NAME: landing-page
  CONTAINER_REGISTRY: landing-pages-01
  NAMESPACE: test
  NAME_SPACE: calvyn
  REPO_FILE: .
  WORKER_IP: ${{ secret.WORKER_IP }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate with DigitalOcean
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry
      run: doctl registry login

    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        build-args: VERSION=${{ env.IMAGE_TAG }}

    - name: Configure Kubernetes credentials
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Replace variables in Kubernetes manifest
      run: |
        sed -i "s|\${PROJECT_NAME}|landing-page|g" .deployments/test.yaml
        sed -i "s|\${NAME_SPACE}|calvyn|g" .deployments/test.yaml
        sed -i "s|\${CONTAINER_REGISTRY}|landing-pages-01|g" .deployments/test.yaml
        sed -i "s|\${IMAGE_TAG}|${{ env.IMAGE_TAG }}|g" .deployments/test.yaml
        sed -i "s|\${WORKER_IP}|${{ env.WORKER_IP }}|g" .deployments/test.yaml

    - name: Copy Repo Manifest to Droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.K3S_VM_IP }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        source: ${{ env.REPO_FILE }}
        target: /root/calvyn/project/

    - name: Update Kubernetes Manifest
      run: |
        sed -i "s|image: .*|image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}|" ${DEPLOYMENT_FILE}
        envsubst < ${DEPLOYMENT_FILE} > ${DEPLOYMENT_FILE}.tmp
        mv ${DEPLOYMENT_FILE}.tmp ${DEPLOYMENT_FILE}
    
    - name: Deploy to K3s via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.K3S_VM_IP }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          echo "Deploying new manifest..."
          kubectl apply -f /root/calvyn/project/.deployments/test.yaml
          # kubectl rollout restart deployment ${{ env.PROJECT_NAME }} -n ${{ env.NAMESPACE }}