name: Docker Image CI/CD to K3s

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: registry.digitalocean.com/archanist-dev
  IMAGE_NAME: landing-pages-01
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate with DigitalOcean
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry
      run: doctl registry login

    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        build-args: VERSION=${{ env.IMAGE_TAG }}

    - name: Configure Kubernetes credentials
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Update Kubernetes manifest with new image tag
      run: |
        sed -i "s|image: registry.digitalocean.com/archanist-dev/landing-pages-01:.*|image: registry.digitalocean.com/archanist-dev/landing-pages-01:${{ env.IMAGE_TAG }}|" .deployments/test.yaml

    - name: Copy Kubernetes manifest to server
      run: |
        scp -i ${{ secrets.SSH_PRIVATE_KEY }} .deployments/test.yaml root@${{ secrets.K3S_VM_IP }}:/root/.deployments/test.yaml

    - name: Deploy to K3s via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.K3S_VM_IP }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          kubectl apply -f /root/.deployments/test.yaml
          kubectl rollout restart deployment landing-pages